export const dataBookingCards = [
  {
    id: 1,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
  {
    id: 2,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
  {
    id: 3,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
  {
    id: 4,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
  {
    id: 5,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
  {
    id: 6,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
  {
    id: 7,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
  {
    id: 8,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
  {
    id: 9,
    title: "Praia dos Carneiros",
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/b9/e6/c6/praia-dos-carneiros-en.jpg?w=2000&h=-1&s=1",
    localizacao: "Tamandaré, PE",
    categoria: "Praia",
    description: "A Praia dos Carneiros está localizada no município de Tamandaré, em Pernambuco, Brasil. É conhecida por suas águas cristalinas, coqueirais e pela Capela de São Benedito à beira-mar. A praia fica a cerca de 96 km de Recife e a 50 km de Porto de Galinhas.",
    rating: "5.0",
  },
];
